# Generated by Django 4.2.4 on 2023-08-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('is_favorite', models.BooleanField()),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
