# Generated by Django 4.2.4 on 2023-08-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('music', '0002_music_has_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='id_artist',
            field=models.ManyToManyField(to='artist.artist'),
        ),
        migrations.DeleteModel(
            name='Music_has_artist',
        ),
    ]
