# Generated by Django 4.2.4 on 2023-08-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('music', '0003_music_id_artist_delete_music_has_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='id_artist',
        ),
        migrations.AddField(
            model_name='music',
            name='id_artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
            preserve_default=False,
        ),
    ]
